blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/workfa-re/app/discussions
    about: Für Fragen, Feedback und allgemeine Diskussionen.

  - name: Dokumentation
    url: https://workfa.re
    about: Offizielle Website und weiterführende Informationen.

  - name: Support & Kontakt
    url: mailto:support@workfare.team
    about: Bei offiziellen Anfragen oder privatem Feedback.
